# Generated by Django 3.1.3 on 2021-01-06 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled', models.DateTimeField()),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('simple', 'simple'), ('in_app', 'in_app')], max_length=20)),
                ('sent_date_time', models.DateTimeField()),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
