# Generated by Django 3.1.3 on 2021-01-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_notification_rapi', '0003_auto_20210106_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='email',
        ),
    ]
