# Generated by Django 3.1.3 on 2021-02-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_notification_rapi', '0006_notification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
