# Generated by Django 3.1.3 on 2021-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_notification_rapi', '0007_auto_20210210_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
